on: [push, pull_request, workflow_dispatch]
jobs:
  validate_schema:
    name: Validate schema
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '9'
      - run: npm test
  validate_canonical_match:
    name: Validate canonical match
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: '11'
      - name: Validate canonical match
        run: make validate-canonical-match
